//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.03.29 at 02:02:23 PM GMT
//

package uk.gov.ons.ctp.response.casesvc.definition;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class CaseCreation {
  protected String partyId;
  protected String collectionExerciseId;
  protected String collectionInstrumentId;
  protected String sampleUnitRef;
  protected String sampleUnitType;
  protected String actionPlanId;
}
